github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "$GOMOD/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/datadog"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   datadog-agent-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo1.maven.org/maven2
    group_id:    com.datadoghq
    artifact_id: dd-java-agent
    source_classifier: sources
